Document: sfc
Title: Debian sfc Manual
Author: <insert document author here>
Abstract: This manual describes what sfc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sfc/sfc.sgml.gz

Format: postscript
Files: /usr/share/doc/sfc/sfc.ps.gz

Format: text
Files: /usr/share/doc/sfc/sfc.text.gz

Format: HTML
Index: /usr/share/doc/sfc/html/index.html
Files: /usr/share/doc/sfc/html/*.html
