.Dd
.Dt FENNEC 8
.Os GNU
.Sh FENNEC
.Nm fennec
.Nd compiles Fennec Fox system
.\"
.Sh SYNOPSIS
.Nm
compiles Fennec Fox system configuration together with the underlying
operating system
.Nm
currently supports only TinyOS
.\"
.Sh AUTHOR
.Nm
Fennec Fox was written by Marcin Szczodrak. 
.\"
.Sh SEE ALSO
.Xr sfc 8
