.Dd
.Dt SFC 8
.Os GNU
.Sh SFC
.Nm sfc
.Nd Swift Fox compiler
.\"
.Sh SYNOPSIS
.Nm
compiles Swift Fox program into Fennec Fox ready-to-deploy
configuration
.Nm
the input files are the .sfp source code program and .sfl 
which stores the library of Fennec Fox modules definitions
.\"
.Sh AUTHOR
.Nm
Swift Fox was written by Marcin Szczodrak. 
.\"
.Sh SEE ALSO
.Xr fennec 8
