#!/bin/bash
# Swift	Fox Compiler v0 .2
# Authors: Vasileios P. Kemerlis, Marcin Szczodrak
# Date: December 4, 2012

# pool with lexer input
POOL_DIR="lex_pool"
# Swift Fox extensions
SF_EXT="*.sfp"
# regression test suite
REG_TEXT="./regtest_lex"
# temporary output
TMP_OUT="/tmp/real_out.sfp"

#verbose
echo "Lexer regression testing"

# test counter
count=0;

# get Swift Fox programs
for PROG in `ls $POOL_DIR/$SF_EXT`; do
	# expected output
	EXP_OUT=$PROG.out

	# call the regression test suite
	$REG_TEXT $PROG > $TMP_OUT
	
	# verbose
	count=$((++count));
	echo -n "    [$count]"
	echo -n `head -n1 $PROG`;
	echo -n ": ";

	# check for expected behavior
	diff $EXP_OUT $TMP_OUT >> /dev/null
	if (( $? == 0 )); then
	       echo -e "\E[32mSuccess\033[0m";
	else
		echo -e "\E[31mFailed ($PROG)\033[0m"
	fi
done
